# Generated by Django 5.1.7 on 2025-04-02 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_modelpatrimonio_ni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpatrimonio',
            name='ni',
            field=models.CharField(max_length=255),
        ),
    ]
