# Generated by Django 5.1 on 2025-03-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_turma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coigo', models.CharField(max_length=255)),
                ('sala', models.CharField(max_length=255)),
                ('capacidade', models.IntegerField()),
                ('responsavel', models.CharField(max_length=255)),
                ('turno', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('S', 'Sabado')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CAI', 'Curso de Aprendizagem Tecnica'), ('CT', 'Curso Tecnico'), ('FIC', 'Formação Inical e Continuada'), ('CS', 'Curso Superior')], max_length=3)),
                ('hora_aula', models.TimeField()),
                ('sigla', models.CharField(max_length=255)),
            ],
        ),
    ]
