# Generated by Django 5.1 on 2025-03-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ambiente_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='coigo',
            new_name='codigo',
        ),
        migrations.AlterField(
            model_name='ambiente',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('S', 'Sabado')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(choices=[('CAI', 'Curso de Aprendizagem Tecnica'), ('CT', 'Curso Tecnico'), ('FIC', 'Formação Inical e Continuada'), ('CS', 'Curso Superior')], default='CT', max_length=3),
        ),
    ]
